### ISSUE TITLE
TODO: accessibility comparison

### ISSUE THREAD

**Issue by kauebraga** [ipeaGIT/avaliacao_intervencoes#3]
- [ ] Inequalities scatterplot + boxplot
- [x] Plot other high capacity transit lines as well
- [x] Change figure layout: top: 2 maps with access (1 before, after); bottom 2 maps with difference (1 abs, 1 rel);
- [x] Format relative difference to percentage;
- [ ] Add gravitational indicator.

**Comment by kauebraga** [comment]
- [ ] colcoar uma cor para as linhas de alta capacidade diferenciando a linha leste (grey90) das demais (grey80)
- [ ] colocar formula da diferenca
- [ ] colcoa escalas diferentes pros mapas de cima e baixo (um virids, outro colorbewer);
- [ ] em cima: basemap com linhas; embaixo: sem basemap;

**Comment by dhersz** [comment]
Podemos fechar esse?

**Comment by kauebraga** [comment]
Yes!
